# Generated by Django 2.1.7 on 2019-07-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoomManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.IntegerField(verbose_name='障碍物的开始行号')),
                ('start_y', models.IntegerField(verbose_name='障碍物的结束行号')),
                ('end_x', models.IntegerField(verbose_name='障碍物的开始列号')),
                ('end_y', models.IntegerField(verbose_name='障碍物的结束列号')),
                ('door_x', models.IntegerField(default=0, verbose_name='障碍物的入口行号')),
                ('door_y', models.IntegerField(default=0, verbose_name='障碍物的入口列号')),
                ('geo_name', models.CharField(max_length=100, null=True, verbose_name='障碍物的名称')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManagement.BuildingFloor', verbose_name='建筑物楼层')),
            ],
            options={
                'verbose_name': '地图栅格',
                'verbose_name_plural': '地图栅格管理',
            },
        ),
    ]
