# Generated by Django 2.1.7 on 2019-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_url', models.URLField(null=True, verbose_name='广告链接')),
                ('ads_image', models.ImageField(null=True, upload_to='AdsImage/%Y/%m/%d', verbose_name='广告图片')),
                ('ads_context', models.TextField(null=True, verbose_name='广告文本内容')),
                ('mac', models.CharField(max_length=50, verbose_name='mac地址')),
            ],
            options={
                'verbose_name': '广告制作',
                'verbose_name_plural': '广告制作管理',
            },
        ),
    ]
