# Generated by Django 2.1.7 on 2019-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0003_ads_ads_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_duration',
            field=models.CharField(default='30s', max_length=15, verbose_name='广告显示时长'),
        ),
    ]
