# Generated by Django 2.1.7 on 2019-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0004_auto_20190726_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_duration',
            field=models.IntegerField(default='30', verbose_name='广告显示时长'),
        ),
    ]
